### ISSUE TITLE
FPS Problem

### ISSUE THREAD

**Issue by JuanTriana** [owaits/avolites-reaperImport#1]
Hi Oliver,

First of all, thanks for creating this great code! 

I am programming a new show but I realized that when I import the markers from Reaper to a cuelist the fps of the cuelist changed to 100fps. I actually working with 30 fps, if I changed the time to 30fps, Titan change all the times. 

I already check that Reaper where in HH:MM:SS:FF and in the project settings the frames are set in 30. 
Attached I send you the CSV.

[No Termino_markers.zip](https://github.com/owaits/avolites-reaperImport/files/4753384/No.Termino_markers.zip)

Thanks in advance for helping me out with this problem.

**Comment by owaits** [comment]
I have added a method to select the frame rate when you load the reaper CSV file. This will allow the timecodes to be set using the correct frame rate. When you import the timecodes it will display in Cue View using the frame rate of the selected timecode source. So it you import a file at 30 FPS but the selected timecode is 100FPS then the timecodes will be displayed using that frame rate. If you change the source to one with the correct frame rate then it will match your CSV file.
